# Generated by Django 4.2.4 on 2023-08-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date_time',
            new_name='created',
        ),
    ]
