# Generated by Django 4.2.4 on 2023-08-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_date_time_todo_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Blog',
        ),
    ]
